import { JobPosting } from './types.js';

export const INITIAL_JOBS: JobPosting[] = [
  {
    id: 'fresher-1',
    job_title: 'Associate AI & ML Engineer (Fresher)',
    company_name: 'UST',
    location: 'Kochi',
    date_posted: '2026-06-13T09:00:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/ust-associate-ai-ml-kochi',
    experience_level: 'Entry Level',
    brief_history: 'UST Kochi Infopark has established a premium center of excellence for Generative AI and deep learning. This designated entry-level pathway recruits fresh engineering graduates, pairing them with lead architects to build edge-computing neural solutions and cloud model gateways.',
    contact_number: '+91 484 661 1100',
    email_id: 'careers.kochi@ust.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format careers.kochi@ust.com is syntactically valid.',
      mxRecords: ['ust.com.mail.protection.outlook.com', 'mxb-001a1a01.gslb.pphosted.com'],
      smtpLog: 'Connected to ust.com.mail.protection.outlook.com on port 25.\nEHLO jobaggregator.local -> 250-mail.protection.outlook.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <careers.kochi@ust.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'fresher-2',
    job_title: 'Graduate Machine Learning Trainee',
    company_name: 'Bosch Engineering',
    location: 'Bangalore',
    date_posted: '2026-06-12T11:30:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/bosch-graduate-ml-trainee-bangalore',
    experience_level: 'Entry Level',
    brief_history: 'Bosch Global Software Technologies (BGSW) Bangalore offers a highly structured Technical Trainee Academy. Fresh graduates undergo rigorous training in digital signal processing, sensor fusion telemetry, and computer vision modeling for advanced automated driving.',
    contact_number: '+91 806 752 1111',
    email_id: 'talent.bgsw@in.bosch.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format talent.bgsw@in.bosch.com is syntactically valid.',
      mxRecords: ['mxa-00100101.bosch.com.pphosted.com', 'mxb-00100101.bosch.com.pphosted.com'],
      smtpLog: 'Connected to mxa-00100101.bosch.com.pphosted.com on port 25.\nEHLO jobaggregator.local -> 250-bosch.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <talent.bgsw@in.bosch.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'job-1',
    job_title: 'Machine Learning Engineer',
    company_name: 'UST',
    location: 'Kochi',
    date_posted: '2026-06-12T10:00:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/ust-ml-engineer-kochi',
    experience_level: 'Mid Level',
    brief_history: 'UST is a leading digital technology solutions company. Founded in 1999 and headquartered in Aliso Viejo, California, UST has a massive presence in Kochi at Infopark, employing thousands of engineers focused on custom AI, cloud computing, and enterprise software platforms.',
    contact_number: '+91 484 661 1100',
    email_id: 'careers.kochi@ust.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format careers.kochi@ust.com is syntactically valid.',
      mxRecords: ['ust.com.mail.protection.outlook.com', 'mxb-001a1a01.gslb.pphosted.com'],
      smtpLog: 'Connected to ust.com.mail.protection.outlook.com on port 25.\nEHLO jobaggregator.local -> 250-mail.protection.outlook.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <careers.kochi@ust.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'fresher-3',
    job_title: 'Junior Computer Vision Associate (Fresher Friendly)',
    company_name: 'InApp',
    location: 'Kochi',
    date_posted: '2026-06-11T13:45:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/inapp-jr-cv-associate-kochi',
    experience_level: 'Entry Level',
    brief_history: 'InApp has specialized software engineering offices in Infopark Kochi. This position targets fresh computer application and software graduates, training them to deploy, debug, and monitor production OpenCV, YOLOv8, and segmentation libraries for retail clients.',
    contact_number: '+91 484 252 8225',
    email_id: 'careers@inapp.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format careers@inapp.com is syntactically valid.',
      mxRecords: ['mail3.inapp.com', 'mail4.inapp.com'],
      smtpLog: 'Connected to mail3.inapp.com on port 25.\nEHLO jobaggregator.local -> 250-inapp.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <careers@inapp.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'job-2',
    job_title: 'Senior Computer Vision Engineer (ADAS)',
    company_name: 'Bosch Engineering',
    location: 'Bangalore',
    date_posted: '2026-06-11T09:15:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/bosch-cv-adas-bangalore',
    experience_level: 'Senior Level',
    brief_history: 'Bosch Global Software Technologies (BGSW), formerly Robert Bosch Engineering and Business Solutions, is an international tech giant in Bangalore, India. Their local team develops advanced driver-assistance systems (ADAS), high-definition maps-rendering, and advanced computer vision frameworks for global automotive brands.',
    contact_number: '+91 806 752 1111',
    email_id: 'talent.bgsw@in.bosch.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format talent.bgsw@in.bosch.com is syntactically valid.',
      mxRecords: ['mxa-00100101.bosch.com.pphosted.com', 'mxb-00100101.bosch.com.pphosted.com'],
      smtpLog: 'Connected to mxa-00100101.bosch.com.pphosted.com on port 25.\nEHLO jobaggregator.local -> 250-bosch.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <talent.bgsw@in.bosch.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'fresher-4',
    job_title: 'Associate Data Scientist (AI/ML)',
    company_name: 'Sigmoid Consulting',
    location: 'Bangalore',
    date_posted: '2026-06-10T16:00:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/sigmoid-assoc-data-scientist-bangalore',
    experience_level: 'Entry Level',
    brief_history: 'Sigmoid Bangalore provides premium software consulting. This junior role welcomes fresh post-graduates or undergrads, placing them in direct client consulting rotations to manage PySpark pipelines and custom MLOps scaling infrastructures.',
    contact_number: '+91 804 125 6130',
    email_id: 'talent-india@sigmoid.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format talent-india@sigmoid.com is syntactically valid.',
      mxRecords: ['aspmx.l.google.com', 'alt1.aspmx.l.google.com'],
      smtpLog: 'Connected to aspmx.l.google.com on port 25.\nEHLO jobaggregator.local -> 250-aspmx.l.google.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <talent-india@sigmoid.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'job-3',
    job_title: 'NLP & Deep Learning Architect',
    company_name: 'IBM India Software Labs',
    location: 'Kochi',
    date_posted: '2026-06-10T14:30:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/ibm-software-labs-kochi-nlp',
    experience_level: 'Senior Level',
    brief_history: 'IBM opened its flagship Software Labs center in Infopark Kochi in 2022. This state-of-the-art hub focuses on product engineering for IBM Cloud, security tools, and advanced Watsonx-powered NLP/GenAI solutions, making Kochi a tier-1 center for IBM global R&D.',
    contact_number: '+91 484 713 5000',
    email_id: 'ibmrnd-kochi-hr@ibm.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format ibmrnd-kochi-hr@ibm.com is syntactically valid.',
      mxRecords: ['mx01.ibm.com', 'mx02.ibm.com'],
      smtpLog: 'Connected to mx01.ibm.com on port 25.\nEHLO jobaggregator.local -> 250-ibm.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <ibmrnd-kochi-hr@ibm.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'job-4',
    job_title: 'AI Platform Research Engineer',
    company_name: 'IISc Computational Labs',
    location: 'Bangalore',
    date_posted: '2026-06-09T08:00:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/iisc-bangalore-ai-platform',
    experience_level: 'Mid Level',
    brief_history: 'The Indian Institute of Science (IISc), founded in 1909 and headquartered in Bangalore, is India\'s top-ranked scientific research institution. The Department of Computational and Data Sciences (CDS) hosts elite research groups working on deep learning hardware codesign, medical imaging, and robust AI platforms.',
    contact_number: '+91 802 293 2228',
    email_id: 'admissions-and-jobs@cds.iisc.ac.in',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format admissions-and-jobs@cds.iisc.ac.in is syntactically valid.',
      mxRecords: ['cds-iisc-ac-in.mail.protection.outlook.com'],
      smtpLog: 'Connected to cds-iisc-ac-in.mail.protection.outlook.com on port 25.\nEHLO jobaggregator.local -> 250-cds.iisc.ac.in\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <admissions-and-jobs@cds.iisc.ac.in> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'job-5',
    job_title: 'Computer Vision & AI Scientist',
    company_name: 'TCS Research',
    location: 'Kochi',
    date_posted: '2026-06-08T11:45:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/tcs-research-kochi-cv-ai',
    experience_level: 'Senior Level',
    brief_history: 'Tata Consultancy Services (TCS), a global IT service leader, hosts specialized research divisions in Infopark Kochi & Whitefield Bangalore. This division focuses heavily on Internet of Things (IoT), Computer Vision for smart agriculture, automation, and advanced deep learning for medical diagnoses.',
    contact_number: '+91 484 664 5000',
    email_id: 'careers.cochin@tcs.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format careers.cochin@tcs.com is syntactically valid.',
      mxRecords: ['tcs-com.mail.protection.outlook.com'],
      smtpLog: 'Connected to tcs-com.mail.protection.outlook.com on port 25.\nEHLO jobaggregator.local -> 250-tcs.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <careers.cochin@tcs.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'job-6',
    job_title: 'Machine Learning Specialist',
    company_name: 'Sigmoid Consulting',
    location: 'Bangalore',
    date_posted: '2026-06-07T16:00:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/sigmoid-ml-specialist-bangalore',
    experience_level: 'Mid Level',
    brief_history: 'Sigmoid is an award-winning data analytics and AI consulting firm headquartered in New York, with its premier engineering hub in Bangalore. They build state-of-the-art recommendation systems, predictive analytics pipelines, and cloud-native MLOps architectures for top retailers and digital natives.',
    contact_number: '+91 804 125 6130',
    email_id: 'talent-india@sigmoid.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format talent-india@sigmoid.com is syntactically valid.',
      mxRecords: ['aspmx.l.google.com', 'alt1.aspmx.l.google.com'],
      smtpLog: 'Connected to aspmx.l.google.com on port 25.\nEHLO jobaggregator.local -> 250-aspmx.l.google.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <talent-india@sigmoid.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'job-7',
    job_title: 'Generative AI Developer',
    company_name: 'InApp',
    location: 'Kochi',
    date_posted: '2026-06-06T13:20:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/inapp-kochi-generative-ai',
    experience_level: 'Mid Level',
    brief_history: 'InApp is an executive software company established in 2000. It opened major software development blocks in Technopark Trivandrum and Infopark Kochi. InApp specializes in enterprise web solutions, IoT systems, and is aggressively integrating Generative AI APIs and custom NLP interfaces into consumer applications.',
    contact_number: '+91 484 252 8225',
    email_id: 'careers@inapp.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format careers@inapp.com is syntactically valid.',
      mxRecords: ['mail3.inapp.com', 'mail4.inapp.com'],
      smtpLog: 'Connected to mail3.inapp.com on port 25.\nEHLO jobaggregator.local -> 250-inapp.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <careers@inapp.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'job-8',
    job_title: 'Deep Learning Software Engineer',
    company_name: 'NVIDIA Hardware Engineering',
    location: 'Bangalore',
    date_posted: '2026-06-05T10:00:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/nvidia-dl-software-bangalore',
    experience_level: 'Mid Level',
    brief_history: 'NVIDIA Bangalore is one of NVIDIA\'s most critical research and design centers globally. It houses elite engineering teams developing CUDA architectures, deep neural net software packages (cuDNN, TensorRT), compiler optimization tools, and drivers for NVIDIA DGX AI supercomputers.',
    contact_number: '+91 806 820 9000',
    email_id: 'blr-talent@nvidia.com',
    enrichment_status: 'completed',
    email_validity: true,
    syntax_valid: true,
    mx_valid: true,
    smtp_valid: true,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format blr-talent@nvidia.com is syntactically valid.',
      mxRecords: ['nvidia-com.mail.protection.outlook.com'],
      smtpLog: 'Connected to nvidia-com.mail.protection.outlook.com on port 25.\nEHLO jobaggregator.local -> 250-nvidia.com\nMAIL FROM: <verify@jobaggregator.local> -> 250 2.1.0 Sender OK\nRCPT TO: <blr-talent@nvidia.com> -> 250 2.1.5 Recipient OK\nSMTP verification completed successfully. Recipient is active.'
    }
  },
  {
    id: 'job-9',
    job_title: 'Junior Machine Learning Analyst',
    company_name: 'Calculus Solutions',
    location: 'Kochi',
    date_posted: '2026-06-04T12:00:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/calculus-solutions-kochi-ml',
    experience_level: 'Entry Level',
    brief_history: 'Calculus Solutions is a growing local AI boutique agency in Kochi Edappally. They build bespoke business automation, text parsing bots, and dashboarding solutions for regional supply chain and logistics clients, using Python, Pandas, and lightweight open-source models.',
    contact_number: '+91 484 416 1111',
    email_id: 'hiring@calculussolutions-tempbrand.co',
    enrichment_status: 'completed',
    email_validity: false,
    syntax_valid: true,
    mx_valid: false,
    smtp_valid: false,
    validation_status: 'completed',
    validation_details: {
      syntaxCheck: 'Email format hiring@calculussolutions-tempbrand.co is syntactically valid.',
      mxRecords: [],
      smtpLog: 'Failed: DNS Query resolved no MX records for domain calculussolutions-tempbrand.co.\nSMTP handshake aborted because the destination domain has no mail exchangers.'
    }
  },
  {
    id: 'job-10',
    job_title: 'AI Solutions Engineer (Associate Track)',
    company_name: 'Cognizant Technology Solutions',
    location: 'Kochi',
    date_posted: '2026-06-03T11:00:00.000Z',
    job_url: 'https://www.linkedin.com/jobs/view/cts-kochi-ai-solutions',
    experience_level: 'Entry Level',
    enrichment_status: 'pending',
    validation_status: 'pending'
  }
];
